- name: Copying rsyslog Config 
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf

- name: Restart rsyslog 
  ansible.builtin.service:
    name: rsyslog 
    state: restarted       
    daemon_reload: yes 