- name: Configuring the nodejs repo 
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: Installing NodeJS 
  ansible.builtin.package:
    name: nodejs 
    state: present 

# Calling User Task from common role
- name: Calling Create User Role From Common
  ansible.builtin.include_role:
    name: common 
    tasks_from: create-user

- name: Downloading the pem key
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/
    mode: '0440'
    owner: roboshop 
    group: roboshop 

# As per the standard application artifacts should be downloaded only from Test Artifacts Only ( Nexus )
# - name: Calling Download and Extract Role From Common
#   ansible.builtin.include_role:
#     name: common 
#     tasks_from: download

- name: Calling Download and Extract Role From Common
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-from-nexus

# Performing NPM Install
- name: Doing Npm Install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

# Call Configure Service Role
- name: Calling Config Service Role From Common
  ansible.builtin.include_role:
    name: common 
    tasks_from: config-svc

- name: Configuring Rsyslog            # This will configure the rules to route the logs to the intended file
  ansible.builtin.include_role:
    name: elk 
    tasks_from: rsyslog

- name: Installing filebeat          # This will install beats on all the servers.
  ansible.builtin.include_role:
    name: elk 
    tasks_from: filebeat

- name: Installing node_exporter          # This will install beats on all the servers.
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter